### PR TITLE
Fix for change in ResourceService::put

### PR DESCRIPTION
**Pull request by ajs6f**

### CODE REVIEW

**Comment by acoburn** [comment]
You'll want to also update [this line](https://github.com/trellis-ldp/trellis-rosid-common/blob/master/build.gradle#L33) to 0.4.1-SNAPSHOT

**Comment by ajs6f** [comment]
Ah, I did that locally, but I wasn't sure if you wanted it in the PR. I'll send it.

**Comment by acoburn** [comment]
There are some checkstyle errors, but otherwise this looks great.

```
[ant:checkstyle] [ERROR] C:\projects\trellis-rosid-common\src\main\java\org\trellisldp\rosid\common\AbstractResourceService.java:138:32: Parameter identifier should be final. [FinalParameters]
[ant:checkstyle] [ERROR] C:\projects\trellis-rosid-common\src\main\java\org\trellisldp\rosid\common\AbstractResourceService.java:138:48: Parameter ixnModel should be final. [FinalParameters]
[ant:checkstyle] [ERROR] C:\projects\trellis-rosid-common\src\main\java\org\trellisldp\rosid\common\AbstractResourceService.java:138:62: Parameter dataset should be final. [FinalParameters]
[ant:checkstyle] [ERROR] C:\projects\trellis-rosid-common\src\main\java\org\trellisldp\rosid\common\AbstractResourceService.java:142: 'if' construct must use '{}'s. [NeedBraces]
```

**Comment by ajs6f** [comment]
Needless braces are the worst, gr... but so be it!

**Comment by ajs6f** [comment]
How do I run a formatting check with `gradlew`?

**Comment by acoburn** [comment]
`./gradlew clean check` should do it

**Comment by acoburn** [comment]
`Future::get` will wait to join the task that's running, but in this case the task hasn't been started. I would assume that a method that returns a `Future<T>` would have already started the task (though the task may not have completed).

**Comment by ajs6f** [comment]
Oh, I see. I left that out because it doesn't make any difference here-- those `FutureTask`s are just a convenient way to return a `Future<>` when we already know the outcome because our persistence is really synchronous anyway, but I can add them for form and future use.

**Comment by ajs6f** [comment]
I used a `CompletableFuture` instead to be crystal clear. Better?

**Comment by acoburn** [comment]
Yes, that is great.

**Pull request merged**
